version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs:master
    container_name: vx_ipfs_host
    volumes:
    - ./ipfs/export:/export
    - ./ipfs/data:/data/ipfs
    - ../config/secrets/ipfs/swarm.key:/data/ipfs/swarm.key
    ports:
    - 5001:5001
    - 4001:4001
    - 8080:8080
