- hosts: docker_containers
  remote_user: sim
  become: true
  tasks:
  - name: Install tools
    apt:
      name: ['htop', 'tmux']
  roles:
    - vx.install-common
    # - vx.install-blender
    # - vx.install-simbotic-engine
