- name: Setting variables to use across plays
  hosts: all
  tasks:
    - set_fact:
        user_to_configure: "{{ansible_user_id}}"

- name: Create vx directories
  hosts: all
  gather_facts: no
  vars:
    vx_root: "{{ansible_env.HOME}}/vx"
  roles:
    - vx.create-directories

- name: Install prerequisite packages and basic tools
  hosts: all
  gather_facts: no
  become: true
  vars:
    vx_root: "{{ansible_env.HOME}}/vx"
  roles:
    - vx.install-common
    - vx.install-basic-tools

- name: Install applications
  hosts: all
  gather_facts: no
  vars:
    vx_root: "{{ansible_env.HOME}}/vx"
  roles:
    - vx.install-blender