- hosts: docker_containers
  vars:
    user_to_configure: racsoraul
  remote_user: "{{user_to_configure}}"
  become: true
  tasks:
  - name: Install tools
    apt:
      name: ['htop', 'tmux']
  roles:
    - vx.install-common
    # - vx.install-blender
    # - vx.install-simbotic-engine
