- hosts: docker_containers
  vars:
    user_to_configure: racsoraul
    vx_root: "{{ansible_env.HOME}}/vx"
  remote_user: "{{user_to_configure}}"
  roles:
    - vx.create-directories
    - vx.install-common
    - vx.install-tools
    # - vx.install-blender
