- name: Setting variables to use across plays
  hosts: vertex
  tasks:
    - set_fact:
        user_to_configure: "{{ansible_user_id}}"
        vx_root: "{{ansible_env.HOME}}/vx"

- name: Create vx directories
  hosts: vertex
  gather_facts: no
  roles:
    - vx.create-directories

- name: Install prerequisite packages and basic tools
  hosts: vertex
  gather_facts: no
  become: true
  roles:
    - vx.install-common
    - vx.install-basic-tools

- name: Install applications
  hosts: vertex
  gather_facts: no
  roles:
    - vx.install-blender