---
# Prerequisites
- name: installing prerequisite packages which let apt use packages over HTTPS
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    update_cache: yes

# Docker
- name: adding docker GPG key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ubuntu_version}} stable"
    state: present
- name: installing docker and related tools
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update-cache: true
- name: create docker group
  group:
    name: docker
    state: present
- name: add user to the docker group
  user:
    name: "{{user_to_configure}}"
    groups: docker
    append: yes
    state: present

# docker-compose
- name: installing docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-{{ansible_system}}-{{ansible_machine}}"
    dest: /usr/local/bin/docker-compose
    mode: 0755

# nvidia-docker
- name: adding nvidia-docker key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present
- name: adding nvidia-docker package repository
  shell: curl -s -L https://nvidia.github.io/nvidia-docker/{{os_release}}/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
  args:
    warn: false
    executable: /bin/bash
- name: sudo apt-get update
  apt:
    update_cache: yes
- name: installing nvidia-docker2
  apt:
    name: "nvidia-docker2"
    update_cache: yes
- name: reloading the Docker daemon configuration
  command: pkill -SIGHUP dockerd